# Config file for https://travis-ci.org/

language: php

# Define the php versions against we want to test our code
php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

# Note: Code coverage requires php-xDebug extension enabled on CI server

install:
- travis_retry composer install --no-interaction --no-suggest

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
- composer test -- --coverage-clover=coverage.xml

before_install:
  -  if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then curl -sL -o ~/.phpenv/versions/5.5/bin/phpunit https://phar.phpunit.de/phpunit-4.8.phar; chmod +x ~/.phpenv/versions/5.5/bin/phpunit; fi
  -  if [[ "(7.0 7.1 7.2 7.3 nightly)" =~ $(phpenv version-name) ]]; then curl -sL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar; chmod +x ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi

#after_script:

after_success:
# Submit coverage report to https://codecov.io
- bash <(curl -s https://codecov.io/bash)

#after_failure:

# Monitor only these branches
branches:
  only:
  - master
  - dev

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/.composer/cache

